### PR TITLE
Feature/first time tips

### PR DESCRIPTION
**Pull request by markyou**

### CODE REVIEW

**Comment by markyou** [comment]
[[iOS] Add the "Add Note" prompt back into Tidepool Mobile](https://trello.com/c/inzAWneu/714-ios-add-the-add-note-prompt-back-into-tidepool-mobile)

**Comment by lakenyon** [comment]
It looks like the following lines from firstTimeHealthKitConnectCheck were inadvertently deleted:
            // One-shot finished!
            oneShotCompleted("ConnectToHealthCelebrationHasBeenShown")
            firstTimeHealthTip.isHidden = false
Without these, the health kit connect tip won't ever be shown.

The overall logic for the tips has gotten pretty complex (haven't had time to simplify it); I tried to outline all the tips and cases where shown and where marked complete. There are a couple odd cases, but I don't think they are worth fixing: (1) I've see a first note not open automatically, but it gets the "Tap to view data" tip shown - I think this case is where this is a first note created; (2) I've seen a case where the first note opens, and no "Tap to view data" is ever shown - I think this is where there are existing notes; (3) Thought I also saw one where the note opens, and then when closing the "Tap to view data" note appeared once.

I also ran into a case where the first note showed busy loading for a very long time: this happened when I had started a long HK sync and gone back to the home screen; since the home screen is continually getting notifications that new data has been uploaded, it keeps trying to refresh the open graphs, which leave them in a busy loading state if no data exists for that time range. When implementing this on the RN version, it would probably be good to get a notification about what the data range is for the uploaded data, so the graph can ignore it if it wasn't for the time pertinent to the graph.

**Comment by markyou** [comment]
The line I deleted that I should have kept was "firstTimeHealthTip.isHidden = false". I moved the oneShotCompleted calls to where the tips are actually dismissed. I'm pushing a fix for this issue shortly

**Comment by lakenyon** [comment]
Looks good!

**Comment by markyou** [comment]
[[iOS] Add the "Add Note" prompt back into Tidepool Mobile](https://trello.com/c/inzAWneu/714-ios-add-the-add-note-prompt-back-into-tidepool-mobile)

**Pull request merged**
